$(document).ready(function(){
  $(".design").click(function(){
      $(".img1").toggle();
      $(".text1").toggle();
  });
  $(".development").click(function(){
      $(".img2").toggle();
      $(".text2").toggle();
  });
  $(".product").click(function(){
      $(".img3").toggle();
      $(".text3").toggle();
  });
});