$(document).ready(function(){
  $(".design").click(function(){
      $(".img1").toggle();
      $(".text1").toggle();
  });
  $(".development").click(function(){
      $(".wedo2").toggle();
      $(".info2").toggle();
  });
  $(".product").click(function(){
      $(".wedo3").toggle();
      $(".info3").toggle();
  });
});